#baseURL =  "https://abbourne.github.io/quickstart/"
#canonifyURLs = false
#disablePathToLowerm = false
#relativeURLs = true  #when set to true, it breaks the 404 page.
languageCode = "en-us"

title = "It's All Downhill From Here"
theme = "mainroad2" # Mainroad2 is my customized version
paginate = "10" # Number of posts per page
enableEmoji = true
#disqusShortname = "" # Enable Disqus comments by entering your Disqus shortname
#googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
  name = "Bill Bourne"
  bio = "Bill Bourne is a cyclist."
  avatar = "img/avatar.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe= true     # Allow HTML in markdown input files
    [markup.goldmark.parser.attribute]
      block = true
  [markup.highlight]
    guessSyntax = true
    style = "monokailight"
    noClasses = true  # Creates styling inline, otherwise inserts css classes

[Params]
  description = "Bill Bourne's personal blog about cycling and stuff" # Site description. Used in meta description
  #copyright = "John Doe" # Footer copyright holder, otherwise will use site title
  customCSS = ["css/custom.css"] # Include custom CSS files
  mainSections = ["blog", "tracknut", "cyclingsafety"]  #Need to include all folders with articles I want on the main page
  opengraph = true
  schema = true
  twitter_cards = true
  post_meta = ["date", "categories", "tags"]
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-MML-AM_CHTML" # Specify MathJax config
# mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  mathjax = true
  pager = true

[Params.style.vars]
  highlightColor = "#0185C1" # Override highlight color
  primaryColor = "#0185C1"   # Used for blocks
  secondaryColor = "#FEEF4D" # Used in titles 
  #fontFamilyPrimary - overrides mainroad theme fonts. san serif fonts
  #fontFamilySecondary - overrides mainroad theme fonts. mono fonts
  #fontFamilyBody - override body fonts in my custom css (serif)
  #fontFamilyHead - override heading fonts in my custom css (serif)
  #fontFamilyMono - override mono (code, etc) fonts in my custom css (serif)

[Params.logo]
  subtitle = "Bill Bourne's Blog"
  image = "img/bicycle-round-yellow.png"

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = true # Enable counter for each category in "Categories" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "abbourne"
  linkedin = "williambourne"
  # github = "abbourne"
  email = "wbbourne@gmail.com"
  strava = "athletes/123225"

[Params.widgets.search]
  url = "https://google.com/search"
  [Params.widgets.search.input]
    name = "sitesearch"
    pre = ""

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["recent", "categories", "social"]
