---
#baseURL: "https://abbourne.github.io/quickstart/"
relativeURLs: true
#canonifyURLs: false
#disablePathToLower: false
languageCode: "en-us"
title: "Bills Hugo Testing Site"
theme: "mainroad"

Params.style.vars:
  highlightColor: "#0B6EEF"
